# Generated by Django 2.1.1 on 2018-12-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='after_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=10)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='booking_room',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('credit_card', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='check_availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_number', models.IntegerField()),
                ('max_numbers', models.IntegerField()),
                ('bed_option', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room_type', models.CharField(max_length=10)),
                ('total_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('hotel_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='roomtype',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='display',
            name='email_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.register'),
        ),
        migrations.AddField(
            model_name='display',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.booking_room'),
        ),
        migrations.AddField(
            model_name='check_availability',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.roomtype'),
        ),
        migrations.AddField(
            model_name='cancel',
            name='email_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.register'),
        ),
        migrations.AddField(
            model_name='cancel',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.booking_room'),
        ),
        migrations.AddField(
            model_name='booking_room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.Hotels'),
        ),
        migrations.AddField(
            model_name='after_booking',
            name='email_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.register'),
        ),
        migrations.AddField(
            model_name='after_booking',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.booking_room'),
        ),
    ]
