# Generated by Django 2.1.1 on 2018-11-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_room',
            fields=[
                ('credit_card', models.IntegerField()),
                ('room_type', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.booking_room')),
            ],
        ),
        migrations.CreateModel(
            name='check_availability',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('username', models.CharField(max_length=100)),
                ('total_cost', models.IntegerField()),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.booking_room')),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='booking_room',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.check_availability'),
        ),
    ]
