# Generated by Django 2.1.1 on 2018-11-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='after_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AlterField(
            model_name='register',
            name='email_id',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='after_booking',
            name='email_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.register'),
        ),
        migrations.AddField(
            model_name='after_booking',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.booking_room'),
        ),
    ]
